### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by ericdke** [aciidb0mb3r/atom-swift-debugger#1]
1. Install Atom (.deb)
2. Install swift-debugger
3. cd MyProject (already has a valid package)
4. atom .
5. e=myexecutable, p=myswiftinstall/usr/bin/swift
6. [run]

**Atom Version**: 1.3.1
**System**: Ubuntu 15.10
**Thrown From**: [swift-debugger](https://github.com/aciidb0mb3r/atom-swift-debugger) package, v0.1.2
### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At internal/child_process.js:298

Error: spawn ENOTDIR
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:351:9)
    at SwiftDebuggerView.module.exports.SwiftDebuggerView.runApp (/home/ed/.atom/packages/swift-debugger/lib/swift-debugger-view.coffee:52:19)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -3:57 swift-debugger:toggle (atom-text-editor.editor.is-focused)
     -2:32 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -1:37.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
 53x -1:22.4.0 core:move-left (atom-text-editor.editor.mini.is-focused)
 42x -1:18.7.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  2x -1:16.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 47x -0:50.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:47.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  9x -0:26.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -0:22.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
language-swift, v0.4.0
swift-debugger, v0.1.2

# Dev
No dev packages
```

**Comment by ericdke** [comment]
I just resolved it, sorry. The issue was I was using "p=/home/me/myswiftinstall/usr/bin/swift" instead of "p=/home/me/myswiftinstall/usr/bin"

**Comment by aciidgh** [comment]
Yeah it's a pain right now, I should make some GUI for selecting path.
