### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by kabamaplaying** [aciidb0mb3r/atom-swift-debugger#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [swift-debugger](https://github.com/aciidb0mb3r/atom-swift-debugger) package, v0.1.2
### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /home/kaleth/.atom/packages/swift-debugger/lib/swift-debugger-view.coffee:39

TypeError: Cannot read property 'getPath' of undefined
    at SwiftDebuggerView.module.exports.SwiftDebuggerView.workspacePath (/home/kaleth/.atom/packages/swift-debugger/lib/swift-debugger-view.coffee:39:24)
    at SwiftDebuggerView.module.exports.SwiftDebuggerView.runApp (/home/kaleth/.atom/packages/swift-debugger/lib/swift-debugger-view.coffee:52:68)
    at HTMLButtonElement.<anonymous> (/opt/atom/resources/app.asar/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
  2x -9:53.6.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -9:52.4.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -9:37.8.0 tree-view:show-in-file-manager (span.name.icon.icon-file-text)
     -3:30.2.0 swift-debugger:toggle (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 21x -2:50.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:42.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:18.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:18.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -2:14.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:43.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:12.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -1:12 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:13.1.0 tree-view:copy-full-path (span.name.icon.icon-file-directory)
     -0:10.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:02.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.9.0 (active)
angularjs, v0.3.5 (active)
autocomplete-go, v1.2.0 (active)
autocomplete-js-import, v1.2.1 (active)
autocomplete-primer, v0.3.1 (active)
autocomplete-swift, v1.0.2 (active)
build-xcodebuild, v0.2.0 (active)
emmet, v2.4.3 (active)
go-config, v1.2.4 (active)
go-get, v2.1.1 (active)
language-swift, v0.4.0 (active)
linter, v1.11.16 (active)
linter-pep8, v1.3.2 (active)
linter-sass-lint, v1.7.1 (active)
linter-swift-package-manager, v0.1.0 (active)
linter-swiftc, v2.0.0 (active)
linter-tidy, v2.2.0 (active)
qolor, v0.4.0 (active)
run-time-ui, v13.37.3 (inactive)
script, v3.10.1 (inactive)
swift-debugger, v0.1.2 (active)
vim-mode, v0.65.1 (active)
vue-autocomplete, v0.1.0 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by dawood772** [comment]
Are you sure that you are using correct swift program?
